language: c

compiler:
     - gcc

git:
     depth: 1

script:
     - cd rsync
     - sudo apt-get update
     - sudo apt-get install python3
     - sudo apt-get install -y python3-pip
     - pip3 install --user commonmark
     - sudo apt-get install -y libxxhash-dev
     - sudo apt-get install -y libzstd-dev
     - sudo apt-get install -y libzlz4-dev
     - ./configure
     - make -j $(nproc)
