language: c

compiler:
     - gcc

git:
     depth: 1

script:
     - cd rsync
     - sudo apt-get install -qq npm
     - npm install cmark-gfm
     - npm install commonmark
     - ./configure
     - make -j $(nproc)
