language: c

compiler:
     - gcc

git:
     depth: 1

script:
     - cd rsync
     - sudo apt-get update
     - sudo apt-get install -y python3-pip
     - pip3 install --user commonmark
     - sudo apt install -y gcc g++ gawk autoconf automake python3-cmarkgfm
     - sudo apt-get install -y acl libacl1-dev
     - sudo apt-get install -y attr libattr1-dev
     - sudo apt-get install -y libxxhash-dev
     - sudo apt-get install -y libzstd-dev
     - sudo apt-get install -y liblz4-dev
     - sudo apt-get install -y libssl-dev
     - ./configure
     - make -j $(nproc)
