language: c

compiler:
     - gcc

git:
     depth: 1

before_install:
     - sudo apt-get update
     - sudo apt-get install python3
     - sudo apt-get install pip3
     - sudo pip3 install --user commonmark

script:
     - cd rsync
     - ./configure
     - make -j $(nproc)
