language: c

compiler:
     - gcc

git:
     depth: 1

script:
     - cd rsync
     - sudo apt-get update
     - sudo apt-get install python3
     - sudo apt-get install -y python3-pip
     - pip3 install --user commonmark
     - ./configure --disable-xxhash --disable-zstd --disable-lz4
     - make -j $(nproc)
