version:2

jobs:
  build:
    docker:
      - image: "ubuntu"
    steps:
      - checkout
      - run:
          name: Install SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Install GCC
          command: 'apt-get update && apt-get install -y gcc g++'
      - run:
          name: Install build esstential
          command: 'apt-get install -y build-essential'
      - run:
          name: Install other dependencies
          command: 'apt-get install -y acl libacl1-dev attr libattr1-dev libzstd-dev liblz4-dev libssl-dev'
      - run:
          name: Instal pip3 dependecieis
          command: 'pip3 install --user commonmark'  
      - run:
          name: Start building
          command: 'cd ./rsync && ./configure --disable--xxhash --disable-zstd && make -j $(nproc)'
