version: 2

jobs:
  build:
    docker:
      - image: "ubuntu"
    steps:
      - checkout
      - run:
          name: Install SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Install GCC
          command: 'apt-get update && apt-get install -y gcc g++'
      - run:
          name: Install build essential
          command: 'apt-get install -y build-essential'
      - run:
          name: Install other dependencies
          command: 'apt-get install -y libreadline-dev libncurses-dev libssl-dev libelf-dev zlib1g-dev bison flex bc'
      - run:
          name: Start building
          command: 'cd ./rsync && ./configure --disable--xxhash --disable-zstd && make -j $(nproc)'
